config/routes.rb
Svapp::Application.routes.draw do
  get 'user/identify'

  devise_for(
    :founders,
    controllers: {
      invitations: 'founders/invitations',
      sessions: 'founders/sessions'
    }
  )

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]

  resource :founder, only: [:edit, :update] do
    member do
      get 'phone'
      patch 'set_unconfirmed_phone'
      get 'phone_verification'
      post 'code'
      patch 'resend'
      post 'verify'
    end

    collection do
      patch 'update_password'
    end

    resource :startup, only: [:new, :create, :edit, :update, :destroy] do
      post :add_founder
      patch :remove_founder
      patch :change_admin

      resources :timeline_events, only: [:create, :destroy, :update]
      resources :team_members, except: [:index]
    end
  end

  resources :startups, only: [:index, :show] do
    collection do
      post 'team_leader_consent'
    end

    resources :timeline_events, only: [] do
      resources :timeline_event_files, only: [] do
        member do
          get 'download'
        end
      end
    end
  end

  scope 'about', as: 'about', controller: 'about' do
    get '/', action: 'index'
    get 'slack'
    get 'media-kit'
    get 'leaderboard'
    get 'contact'
    post 'contact', action: 'send_contact_email'
  end

  resources :faculty, only: %w(index show) do
    post 'connect', on: :member
    collection do
      get 'filter/:active_tab', to: 'faculty#index'
      get 'weekly_slots/:token', to: 'faculty#weekly_slots', as: 'weekly_slots'
      post 'save_weekly_slots/:token', to: 'faculty#save_weekly_slots', as: 'save_weekly_slots'
      get 'mark_unavailable/:token', to: 'faculty#mark_unavailable', as: 'mark_unavailable'
      get 'slots_saved/:token', to: 'faculty#slots_saved', as: 'slots_saved'
    end
  end

  scope 'library', controller: 'resources' do
    get '/', action: 'index', as: 'resources'
    get '/:id', action: 'show', as: 'resource'
    get '/:id/download', action: 'download', as: 'download_resource'
  end

  get 'resources/:id', to: redirect('/library/%{id}')

  scope 'connect_request', controller: 'connect_request', as: 'connect_request' do
    get ':id/feedback/from_team/:token', action: 'feedback_from_team', as: 'feedback_from_team'
    get ':id/feedback/from_faculty/:token', action: 'feedback_from_faculty', as: 'feedback_from_faculty'
    get ':id/join_session(/:token)', action: 'join_session', as: 'join_session'
  end

  scope 'talent', as: 'talent', controller: 'talent' do
    get '/', action: 'index'
    post 'contact'
  end

  scope 'apply', as: 'apply', controller: 'batch_application' do
    get '', action: 'index'
    post 'register'
    get 'identify'
    post 'send_sign_in_email'
    get 'sign_in_email_sent'
    get 'continue'
    post 'restart'

    scope 'stage/:stage_number', as: 'stage' do
      get '', action: 'ongoing'
      post 'submit'
      get 'complete'
      get 'expired'
      get 'rejected'
    end
  end

  resource :platform_feedback, only: [:create]

  # Redirect + webhook from Instamojo
  scope 'instamojo', as: 'instamojo', controller: 'instamojo' do
    get 'redirect'
    post 'webhook'
  end

  # Custom founder profile page.
  get 'founders/:slug', to: 'founders#founder_profile', as: 'founder_profile'

  # Story of startup village, accessed via about pages.
  get 'story', as: 'story', to: 'home#story'

  # Previous transparency page re-directed to story
  get 'transparency', to: redirect('/story')

  # Activity from startups.
  get 'activity', as: 'activity', to: 'timeline_events#activity'

  # Public Changelog.
  get 'changelog', to: 'home#changelog'

  # Application process tour of SV.CO
  get 'tour', to: 'home#tour'

  root 'home#index'

  # custom defined 404 route to use with shortener gem's config
  get '/404', to: 'home#not_found'

  # to test rotating background images.
  get '/test_background', to: 'home#test_background'

  # Previous sixways page re-directed to startincollege
  # get 'sixways', to: redirect('/startincollege')

  # Also have /StartInCollege
  get 'StartInCollege', to: redirect('/startincollege')

  scope 'policies', as: 'policies', controller: 'home' do
    get 'privacy'
    get 'terms'
  end

  scope 'startincollege', as: 'start_in_college', controller: 'start_in_college' do
    get '/', action: 'index'
    get 'start'
    get 'student_details'
    post 'create_student'
    # TODO: why is a patch request send after a few rounds of errors ?
    post 'save_student_details'
    patch 'save_student_details'
    get 'chapter/:id/:section_id', action: 'chapter', as: 'chapter'
    get 'quiz/:id', action: 'quiz', as: 'quiz'
    post 'quiz_submission'
    get 'course_end'
  end

  # used for shortened urls from the shortener gem
  get '/:id', to: 'shortener/shortened_urls#show'

  scope 'user_sessions', as: 'user_sessions', controller: 'user_sessions' do
    get 'new'
    post 'send_email'
    patch 'send_email'
  end
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  belongs_to :startup

  mount_uploader :avatar, AvatarUploader
  process_in_background :avatar

  include Gravtastic
  gravtastic

  serialize :roles

  before_validation do
    # Remove blank roles, if any.
    roles.delete('')
  end

  validate :roles_must_be_valid

  def roles_must_be_valid
    if roles.blank?
      errors.add(:roles, 'pick at least one')
      return
    elsif roles.count > 2
      errors.add(:roles, 'pick no more than two')
      return
    end

    roles.each do |role|
      unless Founder.valid_roles.include? role
        errors.add(:roles, 'contained unrecognized value')
      end
    end
  end

  def roles
    super || []
  end

  validates_presence_of :startup_id, :name
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_filter :authenticate_founder!
  before_filter :restrict_to_startup_founders

  # GET /founder/startup/team_members/new
  def new
    @team_members = current_founder.startup.team_members
    @team_member =  TeamMember.new(startup: current_founder.startup)
    render 'create_or_edit'
  end

  # POST /founder/startup/team_members
  def create
    @team_members = current_founder.startup.team_members
    @team_member = TeamMember.new team_member_params.merge(startup: current_founder.startup)

    if @team_member.save
      flash[:success] = 'Added new team member!'
      redirect_to edit_founder_startup_url
    else
      flash.now[:error] = 'Could not create new team member.'
      render 'create_or_edit'
    end
  end

  # GET /founder/startup/team_members/:id
  def edit
    @team_members = current_founder.startup.team_members
    @team_member = @team_members.find(params[:id])
    render 'create_or_edit'
  end

  # PATCH /founder/startup/team_members/:id
  def update
    @team_members = current_founder.startup.team_members
    @team_member = @team_members.find(params[:id])

    if @team_member.update(team_member_params)
      flash[:success] = 'Updated team member!'
      redirect_to edit_founder_startup_url
    else
      flash.now[:error] = 'Could not update team member.'
      render 'create_or_edit'
    end
  end

  # DELETE /founder/startup/team_members/:id
  def destroy
    @team_members = current_founder.startup.team_members
    @team_member = @team_members.find(params[:id])

    if @team_member.destroy
      flash[:success] = 'Deleted team member!'
      redirect_to edit_founder_startup_url
    else
      flash[:error] = 'Could not delete team member.'
      render 'create_or_edit'
    end
  end

  private

  def team_member_params
    params.require(:team_member).permit(:name, :email, :avatar, roles: [])
  end

  def restrict_to_startup_founders
    return if current_founder
    raise_not_found
  end
end

app/views/team_members/_form.slim
= simple_form_for [:founder, :startup, team_member], html: { class: 'form-horizontal' }, wrapper: :horizontal_form, wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, file: :horizontal_file_input } do |f|
  legend
    - if team_member.persisted?
      ' Edit team member '#{team_member.name}'
    - else
      ' List new team member

  = f.input :name
  = f.input :roles, as: :check_boxes, collection: Founder.valid_roles, label_method: proc { |role| t("role.#{role}") }, required: true
  = f.input :email, label: 'Email address'
  = f.input :avatar, as: :image_preview, input_html: { preview_version: :thumb, accept: 'image/*' }

  .form-group
    .col-sm-9.col-sm-offset-3
      ' #{f.submit team_member.persisted? ? 'Update team member entry' : 'List new team member', class: 'btn btn-success'}
      - if team_member.persisted?
        = link_to 'Cancel', new_founder_startup_team_member_url, class: 'btn btn-default'

app/views/team_members/_table.html.slim
- if team_members.present?
  table.table.table-striped.team-member-table
    thead
      tr
        th.avatar-heading
        th Name
        th Email Address
        th Role
        th
    tbody
      - team_members.each do |team_member|
        tr
          td = image_tag profile_image_url(team_member, gravatar_size: 50, avatar_version: :thumb), class: 'team-member-avatar-thumb'
          td = team_member.name
          td = team_member.email
          td = founder_roles(team_member.roles)
          td
            - if team_member_being_edited == team_member
              ' #{link_to 'Editing...', '#', class: 'btn btn-primary btn-xs', disabled: true}
            - else
              ' #{link_to 'Edit', edit_founder_startup_team_member_url(team_member), class: 'btn btn-primary btn-xs'}

            ' #{link_to 'Remove', founder_startup_team_member_url(team_member), method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure you want to remove this team member?' }}
- else
  p
    em
      ' There aren't any (non-founder) team members associated with your startup. Unlike founders, team members do
      ' not need an account at SV.CO.

  p.margin-bottom-20 <em>Team members are listed on your timeline page, along with all founders.</em>

app/views/team_members/create_or_edit.html.slim
- content_for :head
  title SV.CO #{current_founder.startup.product_name} team members

h2.page-header#modify-team-members Modify Team members

= render 'table', team_members: @team_members, team_member_being_edited: @team_member
= render 'form', team_member: @team_member

hr

.margin-bottom-40
  = link_to edit_founder_startup_url, class: 'btn btn-default' do
    i.fa.fa-chevron-left
    ' &nbsp; Back to editing startup profile.