config/routes.rb
Svapp::Application.routes.draw do
  get 'user/identify'

  devise_for(
    :founders,
    controllers: {
      invitations: 'founders/invitations',
      sessions: 'founders/sessions'
    }
  )

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]

  resource :founder, only: [:edit, :update] do
    member do
      get 'phone'
      patch 'set_unconfirmed_phone'
      get 'phone_verification'
      post 'code'
      patch 'resend'
      post 'verify'
    end

    collection do
      patch 'update_password'
    end

    resource :startup, only: [:new, :create, :edit, :update, :destroy] do
      post :add_founder
      patch :remove_founder
      patch :change_admin

      resources :timeline_events, only: [:create, :destroy, :update]
      resources :team_members, except: [:index]
    end
  end

  resources :startups, only: [:index, :show] do
    collection do
      post 'team_leader_consent'
    end

    resources :timeline_events, only: [] do
      resources :timeline_event_files, only: [] do
        member do
          get 'download'
        end
      end
    end
  end

  scope 'about', as: 'about', controller: 'about' do
    get '/', action: 'index'
    get 'slack'
    get 'media-kit'
    get 'leaderboard'
    get 'contact'
    post 'contact', action: 'send_contact_email'
  end

  resources :faculty, only: %w(index show) do
    post 'connect', on: :member
    collection do
      get 'filter/:active_tab', to: 'faculty#index'
      get 'weekly_slots/:token', to: 'faculty#weekly_slots', as: 'weekly_slots'
      post 'save_weekly_slots/:token', to: 'faculty#save_weekly_slots', as: 'save_weekly_slots'
      get 'mark_unavailable/:token', to: 'faculty#mark_unavailable', as: 'mark_unavailable'
      get 'slots_saved/:token', to: 'faculty#slots_saved', as: 'slots_saved'
    end
  end

  scope 'library', controller: 'resources' do
    get '/', action: 'index', as: 'resources'
    get '/:id', action: 'show', as: 'resource'
    get '/:id/download', action: 'download', as: 'download_resource'
  end

  get 'resources/:id', to: redirect('/library/%{id}')

  scope 'connect_request', controller: 'connect_request', as: 'connect_request' do
    get ':id/feedback/from_team/:token', action: 'feedback_from_team', as: 'feedback_from_team'
    get ':id/feedback/from_faculty/:token', action: 'feedback_from_faculty', as: 'feedback_from_faculty'
    get ':id/join_session(/:token)', action: 'join_session', as: 'join_session'
  end

  scope 'talent', as: 'talent', controller: 'talent' do
    get '/', action: 'index'
    post 'contact'
  end

  scope 'apply', as: 'apply', controller: 'batch_application' do
    get '', action: 'index'
    post 'register'
    get 'identify'
    post 'send_sign_in_email'
    get 'sign_in_email_sent'
    get 'continue'
    post 'restart'

    scope 'stage/:stage_number', as: 'stage' do
      get '', action: 'ongoing'
      post 'submit'
      get 'complete'
      get 'expired'
      get 'rejected'
    end
  end

  resource :platform_feedback, only: [:create]

  # Redirect + webhook from Instamojo
  scope 'instamojo', as: 'instamojo', controller: 'instamojo' do
    get 'redirect'
    post 'webhook'
  end

  # Custom founder profile page.
  get 'founders/:slug', to: 'founders#founder_profile', as: 'founder_profile'

  # Story of startup village, accessed via about pages.
  get 'story', as: 'story', to: 'home#story'

  # Previous transparency page re-directed to story
  get 'transparency', to: redirect('/story')

  # Activity from startups.
  get 'activity', as: 'activity', to: 'timeline_events#activity'

  # Public Changelog.
  get 'changelog', to: 'home#changelog'

  # Application process tour of SV.CO
  get 'tour', to: 'home#tour'

  root 'home#index'

  # custom defined 404 route to use with shortener gem's config
  get '/404', to: 'home#not_found'

  # to test rotating background images.
  get '/test_background', to: 'home#test_background'

  # Previous sixways page re-directed to startincollege
  # get 'sixways', to: redirect('/startincollege')

  # Also have /StartInCollege
  get 'StartInCollege', to: redirect('/startincollege')

  scope 'policies', as: 'policies', controller: 'home' do
    get 'privacy'
    get 'terms'
  end

  scope 'startincollege', as: 'start_in_college', controller: 'start_in_college' do
    get '/', action: 'index'
    get 'start'
    get 'student_details'
    post 'create_student'
    # TODO: why is a patch request send after a few rounds of errors ?
    post 'save_student_details'
    patch 'save_student_details'
    get 'chapter/:id/:section_id', action: 'chapter', as: 'chapter'
    get 'quiz/:id', action: 'quiz', as: 'quiz'
    post 'quiz_submission'
    get 'course_end'
  end

  # used for shortened urls from the shortener gem
  get '/:id', to: 'shortener/shortened_urls#show'

  scope 'user_sessions', as: 'user_sessions', controller: 'user_sessions' do
    get 'new'
    post 'send_email'
    patch 'send_email'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @skip_container = true
    @sitewide_notice = true if %w(startupvillage.in registration).include?(params[:redirect_from])
    render layout: 'home'
  end

  def story
    @skip_container = true
    render layout: 'application_v2'
  end

  # used by the 'shortener' gem's config
  def not_found
    raise_not_found
  end

  # GET /changelog
  def changelog
    @skip_container = true
    @changelog = File.read(File.absolute_path(Rails.root.join('CHANGELOG.md')))
    render layout: 'application_v2'
  end

  # GET /tour
  def tour
    @skip_container = true
    @batches_open = Batch.open_for_applications
    render layout: 'application_v2'
  end

  def test_background
    # Background image cycling test.
  end

  # GET /policies/privacy
  def privacy
    privacy_policy = File.read(File.absolute_path(Rails.root.join('privacy_policy.md')))
    render text: Kramdown::Document.new(privacy_policy).to_html.html_safe
  end

  # GET /policies/terms
  def terms
    terms_of_use = File.read(File.absolute_path(Rails.root.join('terms_of_use.md')))
    render text: Kramdown::Document.new(terms_of_use).to_html.html_safe
  end

  protected

  def hero_text_number
    @hero_text_number ||= begin
      session[:hero_text_numbers] ||= {}.to_json
      hero_text_numbers = JSON.parse(session[:hero_text_numbers])
      key = background_image_number.to_s
      hero_text_numbers[key] ||= rand(2) + 1
      hero_text_numbers[key] += 1
      hero_text_numbers[key] = 1 if hero_text_numbers[key] > 2
      session[:hero_text_numbers] = hero_text_numbers.to_json
      hero_text_numbers[key]
    end
  end

  def background_image_number
    @background_image_number ||= begin
      session[:background_image_number] ||= rand(4) + 1
      session[:background_image_number] += 1
      session[:background_image_number] = 1 if session[:background_image_number] > 4
      session[:background_image_number]
    end
  end

  def hero_text_alignment
    @hero_text_alignment ||= begin
      {
        1 => 'center',
        2 => 'right',
        3 => 'right',
        4 => 'right',
        5 => 'center' # TODO: Note that this fifth image (SYM's) is disabled.
      }[background_image_number]
    end
  end

  helper_method :background_image_number
  helper_method :hero_text_alignment
  helper_method :hero_text_number
end

app/helpers/home_helper.rb
module HomeHelper
  # TODO: Rewrite to showcase events from the leaderboard toppers of all running batches, if available
  def timeline_events_to_showcase(event_count)
    # if there is no current batch, just return the latest timeline_events which can be showcased
    return TimelineEvent.showcase.limit(3) unless Batch.current.present?

    leading_startup_ids = Startup.leaderboard_toppers_for_batch Batch.current, count: event_count
    leading_startup_ids.map { |startup_id| Startup.find(startup_id).showcase_timeline_event }.compact
  end

  def activity_class_for_count(count)
    if count == 0
      'activity-blank'
    elsif count <= 5
      'activity-low'
    elsif count <= 10
      'activity-medium'
    else
      'activity-high'
    end
  end

  def startup_village_redirect?
    params[:redirect_from] == 'startupvillage.in'
  end

  def registration_redirect?
    params[:redirect_from] == 'registration'
  end
end

app/views/home/_about_links.html.slim
#about-links
  - if feature_active? :transparency_page
    h4.header-light Transparency
    .list-group
      a.list-group-item href="#{about_transparency_path}" Founding Agreements
      a.list-group-item href="#{about_transparency_path}#rtis-received" RTIs Received
  h4.header-light Contact
  .list-group
    a.list-group-item href="#{about_slack_path}" Slack
    a.list-group-item href="mailto:help@sv.co" Email help@sv.co
    - if feature_active? :about_press_kit
      a.list-group-item href="#{about_press_kit_path}" Press Kit
  h4.header-light Startups
  .list-group
    a.list-group-item href="#{about_leaderboards_path}" Leaderboards
  
  h4.header-light Social Media
  .list-group 
    a.list-group-item href="https://www.youtube.com/user/TheStartupVillage" Youtube Page
    a.list-group-item href="https://twitter.com/startatsv" Twitter Account
    a.list-group-item href="https://www.facebook.com/startupvillage" Facebook Page

app/views/home/_blog_posts.html.slim
section.blog-posts
  .blog-heading
    h2 Buzz
    p Latest picks from our blog

  #blog-posts-container
    #blog-posts-loading
      p.text-center
        i.fa.fa-refresh.fa-spin
        | &nbsp; Loading blog posts...
    #blog-posts-loading-failed.hidden
      p.text-center
        i.fa.fa-warning
        ' &nbsp; Couldn't load blog posts!
      p.text-center
        ' We're sorry. :-( You could try
        a href="https://blog.sv.co" visiting our blog
        | &nbsp;instead...
    #post-scaffold.blog-post.hidden
      .blog-post-top
        a.blog-post-image-link href="#"
          /img.blog-post-image src="#add-this-tag-through-javascript"
        .blog-body
          a.blog-post-title-link href="#"
            h5.blog-post-title
          p.blog-post-content
      .blog-post-bottom.flex-center
        a.blog-post-link.btn.btn-default href="#"
          | Continue Reading &raquo;

app/views/home/_stages.html.slim
section.stages
  .container
    .row
      .stages-detail
        h2 Stages & Learning
        p At Startup Village, we're guiding startups through five stages of creating a great startup.

        /stages as carousel
        #stages-carousel.carousel.slide data-ride='carousel'
          / slides
          .carousel-inner role='listbox'
            .item.active
              = image_tag 'stage1.png', class: 'img-responsive'
              p At <strong>IDEA DISCOVERY</strong>, startups discover a product idea that solves a clear user need.
            .item
              = image_tag 'stage2.png', class: 'img-responsive'
              p Then at <strong>PROTOTYPING</strong>, startups develop a working application that's a solution to the idea.
            .item
              = image_tag 'stage3.png', class: 'img-responsive'
              p <strong>CUSTOMER VALIDATION</strong> is when startups find early customers who pay for the product through money or attention.
            .item
              = image_tag 'stage4.png', class: 'img-responsive'
              p At <strong>EFFICIENCY</strong>, startups get more customers leading to a predictable business model.
            .item
              = image_tag 'stage5.png', class: 'img-responsive'
              p And finally startups <strong>SCALE</strong> when they try to aggressively expand and grow.

            .item
              a href="http://playbook.sv.co/"
                = image_tag 'playbook-cover.png', class: 'img-responsive'
              p Our Startup Playbook guides all founders through these startup stages.

          / Controls
          a.left.carousel-control href="#stages-carousel" role="button" data-slide="prev"
            span.glyphicon.glyphicon-chevron-left aria-hidden="true"
            span.sr-only Previous

          a.right.carousel-control href="#stages-carousel" role="button" data-slide="next"
            span.glyphicon.glyphicon-chevron-right aria-hidden="true"
            span.sr-only Next

        a.btn.btn-flat.btn-playbook href="http://playbook.sv.co/" type="button"
            | Read our Playbook

app/views/home/_testimonials.html.slim
section.testimonials
  .container
    #testimonials-carousel.carousel.slide data-ride='carousel'
      / Indicators
      ol.carousel-indicators
        li.active data-target="#testimonials-carousel" data-slide-to="0"
        li data-target="#testimonials-carousel" data-slide-to="1"
        li data-target="#testimonials-carousel" data-slide-to="2"
        li data-target="#testimonials-carousel" data-slide-to="3"
        li data-target="#testimonials-carousel" data-slide-to="4"
        li data-target="#testimonials-carousel" data-slide-to="5"

      .carousel-inner role='listbox'
        .item.active
          .item-flex-center
            div
              .quote-text Awesome place &amp; great ideas with terrific people.
              = image_tag 'testimonials/richard_verma.png', class: 'quote-author-image'
              .quote-author-name Richard Verma
              .quote-author-title United States Ambassador to India
        .item
          .item-flex-center
            div
              .quote-text
                | Changing India! Amazed to see Startup Village. What impressed me is two things:
                br
                | 1. How young the founders are. 2. The variety in startups.
              = image_tag 'testimonials/rajan_anandan.png', class: 'quote-author-image'
              .quote-author-name Rajan Anandan
              .quote-author-title Vice President & Managing Director of Google, South East Asia & India
        .item
          .item-flex-center
            div
              .quote-text Truly Incredible. Continue to Create, Inspire &amp; Lead the world!
              = image_tag 'testimonials/philip_a_min.png', class: 'quote-author-image'
              .quote-author-name Philip A. Min
              .quote-author-title United States Consul General, Chennai
        .item
          .item-flex-center
            div
              .quote-text
                | I think Startup Village is phenomenal.
                br
                | When we have the next billion dollar company from India,
                br
                | we will look back to the seats that started at Startup Village.
              = image_tag 'testimonials/krithiga_reddy.png', class: 'quote-author-image'
              .quote-author-name Krithiga Reddy
              .quote-author-title Director of Online Operations and Head of Office, Facebook India
        .item
          .item-flex-center
            div
              .quote-text
                | What an awesome experience! The passion from people, young entrepreneurs...
                br
                | The real Silicon Valley in the making.
              = image_tag 'testimonials/chakrapani_g_k.png', class: 'quote-author-image'
              .quote-author-name Chakrapani G. K.
              .quote-author-title Head, Microsoft Consumer Channel Group
        .item
          .item-flex-center
            div
              .quote-text
                | Lots of passion... lots of energy.
                br
                | What I really loved is the diversity of ideas
                br
                | and trying to curate that kind of an ecosystem is a fantastic idea.
              = image_tag 'testimonials/nishant_rao.png', class: 'quote-author-image'
              .quote-author-name Nishant Rao
              .quote-author-title Country Manager, LinkedIn India & Chairman, IAMAI

      / Controls
      a.left.carousel-control href="#testimonials-carousel" role="button" data-slide="prev"
        span.glyphicon.glyphicon-chevron-left aria-hidden="true"
        span.sr-only Previous

      a.right.carousel-control href="#testimonials-carousel" role="button" data-slide="next"
        span.glyphicon.glyphicon-chevron-right aria-hidden="true"
        span.sr-only Next

app/views/home/_timeline_events.html.slim
section.timeline-events
  .timeline-event-heading
    h2 Latest Verified Events

  #timeline-events-container
    - timeline_events_to_showcase(3).each do |event|
      .timeline-event
        .timeline-event-top
          .timeline-event-image class="#{event.image_url.present? ? '' : 'timeline-event-bg-size'} event-bgcolor-#{cycle *((1..14).to_a)}" style="background-image: url(#{event.image_url.present? ? event.image_url : event.timeline_event_type.badge});"
          .timeline-event-body
            h5.timeline-event-title #{event.startup.product_name}: #{event.title}
            p.timeline-event-content #{event.description.truncate(140, separator: ' ')}
        a.timeline-event-link.btn.btn-default href="#{startup_url(event.startup, anchor:"event-#{event.id}")}"  target="_blank"
          | View on Timeline
  .timeline-event-message
    p Every startup gets a Timeline where they can submit events that are verified by SV.CO Faculty.

    a.btn.btn-flat.btn-playbook-timeline href="#{activity_path}" type="button"
      | View More

app/views/home/about.html.slim
- content_for :head
  = stylesheet_link_tag 'about'

<ol class="breadcrumb">
  <li><a href="#{root_path}">Home</a></li>
  <li class="active">About</li>
</ol>

h1.page-header.header-light About Startup Village

.row
  .col-sm-7
    #about-main.about-text
      p Startup Village aims to bring the tools and resources to create great startups to every founder in India. We believe that amazing technology startups should not be restricted to big cities, and that everybody can build products: even while you are still in college.

      p We're best known for our inclusive public-private partnership incubator based in Kochi that has <a href="http://yourstory.com/2015/05/startup-village-national-award/">won numerous awards</a> and created stellar startups. The incubator was started in April 2012 as a joint partnership with the Government of India through the <a href="http://www.dst.gov.in">Department of Science and Technology</a>, <a href="http://www.technoparktbi.org">Technopark TBI</a> and our host-institute, <a href="http://mobme.in">MobME Wireless</a>.

      p Building on our knowledge acquired from mentoring startups, we're now launching an online-first learning platform for first-time founders. SV.CO is the first learning platform for entrepreneurship that verifies results & rewards founders with a real degree by partnering with recognized Universities.
      
  .col-sm-3
    = render partial: 'about_links'

app/views/home/apply.html.slim
- content_for :head
  title SV.CO Apply Now
  meta name="description" content="SV.CO helps a team of students develop an idea, build a prototype and collect feedback from early customers."

.container
  .apply-banner
    .row
      .col-md-4
        h1 Apply Now
        p.header-light
          ' We help teams of students develop an idea, build a prototype and
          | collect feedback from early customers.
.apply-container
  .container
    .row
      .col-md-7
        .graduate-details
          h2.header-light
            ' SV.CO is a six month &#8220;Build a Startup&#8221; program for college students.
            ' We help teams of students develop an idea, build a prototype and
            | collect feedback from early customers.
            
          h2.header-light
            ' Every SV.CO batch has a theme: an industry sector where all selected startups focus. The theme of this batch is 
            a href="https://en.wikipedia.org/wiki/Software_as_a_service" Software as a Service (SaaS).

          .students-steps
            h3
              ' At the end of the program, students will:
            ul.apply-step-list.list-unstyled.header-light
              li
                span.apply-icon.deck-icon
                .get-text Create a great product deck
              li
                span.apply-icon.prototype-icon
                .get-text Build a functional &amp; usable prototype
              li
                span.apply-icon.launch-icon
                .get-text Launch a product to customers
              li
                span.apply-icon.iterate-icon
                .get-text Iterate or pivot based on customer feedback

          .students-steps
            h3 Graduating Students will:
            ul.apply-step-list.list-unstyled.header-light
              li
                span.apply-icon.job-offer-icon
                .get-text Get potential acquihire &amp; job offers from great startups
              li
                span.apply-icon.investor-icon
                .get-text Get funding from the best angel investors in the country
              li
                span.apply-icon.entry-icon
                .get-text Have an opportunity to get direct entry into product accelerators

          .highlight-blue.header-light
            | This is the first program of its kind in India where you can learn to build a great startup
            span.font-weight-400>  even while you are still in college.

          .second-batch
            h3 This is the 2nd batch intake for the SV.CO program.
            p We had some amazing Startups in our #{link_to 'first batch', startups_path}. Videos of previous graduates and a program overview is available #{link_to 'on our home page', root_path}.

          .important-dates
            h3.font-weight-400 
              i.fa.fa-calendar-check-o 
              | Important Dates
            ul.important-date-list.list-unstyled.header-light
              li
                span.date-colum
                  span.important-month January
                  span.important-date 5
                  span.important-year 2016
                .date-event 
                  | Deadline for Application
              li
                span.date-colum
                  span.important-month January
                  span.important-date 15
                  span.important-year 2016
                .date-event
                  | Deadline for Video and Code Submission 
              li
                span.date-colum
                  spanspan.important-month January
                  span.important-date 25
                  span.important-year 2016
                .date-event
                  | Team Interview 
              li
                span.date-colum
                  spanspan.important-month February
                  span.important-date 01
                  span.important-year 2016
                .date-event 
                  | On Boarding of Teams 

          .faq
            h3.font-weight-400 
              i.fa.fa-question-circle
              | FAQ
            ul.list-unstyled
              li
                .faq-question 1. How much time do I have to commit to the program?
                .faq-answer 
                  ' At least 10 hours a week. The program is intended to be 
                  ' completed while you are still in college, and we'll make
                  ' allowances for your regular academic schedule,  exams
                  ' and assignment submissions.
              li
                .faq-question 2. Can I join as an individual founder?
                .faq-answer
                  ' No. Only teams of founders can apply and will be selected on merit.
                  ' At least <strong> 3 founders and a maximum of 5</strong> per team. Founders
                  ' should have a mix of engineering ability and speaking &amp; hustling skills.
              li
                .faq-question 3. Who can apply?
                .faq-answer
                  ' Currently, applications <strong>are open to all college students in Andhra Pradesh, Gujarat and Kerala</strong>. In Andhra Pradesh, the programme is offered in partnership with JNTU
                  ' #{link_to 'Anantpur', 'http://jntua.ac.in', target: '_blank'}
                  ' and 
                  ' #{link_to 'Kakinada', 'http://jntuk.edu.in', target: '_blank'}. In Gujarat, the University partners are #{link_to 'Gujarat Technological University', 'http://www.gtu.ac.in', target: '_blank'} and #{link_to 'Gujarat Law Society', 'http://www.gujaratlawsociety.org', target: '_blank'}. Successful graduates will get a Specialisation in Entrepreneurship degree from these Universities.
                  ' Founders have to be in <strong>Semester 5 (third year) or above</strong> to apply.
              li
                .faq-question 4. Do I need to have a product idea to join?
                .faq-answer
                  ' No you do not. Teams will be selected based on engineering and
                  ' speaking/hustling ability and <strong>not on the merit of their product
                  ' idea</strong>. SV.CO has partnered with 
                  ' <strong>#{link_to 'Tracxn Labs', 'http://tracxn.com', target: '_blank'}</strong>
                  ' to provide 50 viable product ideas in the SaaS sector for this
                  ' batch that teams can select after admission.
              li
                .faq-question 5. How much do I have to pay for the program?
                .faq-answer
                  ' Selected teams in this batch get a full scholarship
                  ' (usually a ₹15,000/founder/semester fee). All selected founders
                  ' will have to sign 
                  ' <strong>#{link_to 'legal agreements with SV.CO', 'https://playbook.sv.co/2-legal-agreement.html'}</strong>
                  ' to join the program.
            p
              ' To learn more about the program, visit our #{link_to 'Website', root_url}
              ' and our #{link_to 'Startup Playbook', 'https://playbook.sv.co/'}.
      .col-md-5
        .apply-form
          <iframe id="typeform-full" width="100%" height="100%" frameborder="0" src="https://svlabs.typeform.com/to/V5VSfj"></iframe>

app/views/home/changelog.html.slim
.secondary-banner
  .container
    .col-md-5.col-sm-5
      .banner-head
        h1 Changelog
        p
          | Weekly updates. Regular iteration FTW!
    .col-md-7.changelog-bg

.container
  .container-md-center.content-box.changelog-section.m-t-3.m-b-3
    == Kramdown::Document.new(@changelog).to_html.html_safe

app/views/home/index.html.slim
- content_for :head
  meta property="og:title" content="SV.CO"
  meta property="og:type" content="website"
  meta property="og:url" content=root_url
  meta property="og:image" content=image_url('logo.png')

- if startup_village_redirect?
  - content_for :sitewide_notice
    ' <strong>SV.CO</strong> is the next phase of the Startup Village story.
    ' #{link_to 'Read more here', 'https://sv.co/cwlg8', class: 'btn btn-sm', target: '_blank'}

- if registration_redirect?
  - content_for :sitewide_notice
    ' You have successfully registered on SV.CO. Please wait for your team lead to complete registration.

- content_for :head
  title SV.CO: India’s No 1 Digital Incubator For Students
  meta name="description" content="SV.CO, or Startup Village is a learning platform for entrepreneurs that verifies results, and rewards founders with a real degree from partner Universities."

- content_for :header

.big-container
  .full-screen-background class="background-image-#{background_image_number}"
    .container
      .header-container class="header-#{hero_text_alignment}"
        .hero-text class="hero-text-#{hero_text_alignment}"
          h1 = t("home.index.main_bleed_message_html")
          h4 = t("home.index.background_#{background_image_number}_messages.secondary_html")
          = link_to 'Apply Now', apply_path, class: 'btn btn-primary btn-lg text-uppercase home-apply-btn'
    == render 'layouts/home_footer'

script data-align="right"  data-overlay="false" id="keyreply-script" src="//keyreply.com/chat/widget.js" data-color="#32B475" data-apps="JTdCJTIydHdpdHRlciUyMjolMjJAU1Zkb3RDTyUyMiwlMjJmYWNlYm9vayUyMjolMjIxMDg2NDYxNzkyNTkzNzMlMjIsJTIyZW1haWwlMjI6JTIyaGVscEBzdi5jbyUyMiU3RA=="

app/views/home/press_kit.html.slim
- content_for :head
  = stylesheet_link_tag 'about'
  
<ol class="breadcrumb">
  <li><a href="#{root_path}">Home</a></li>
  <li><a href="#{about_path}">About</a></li>
  <li class="active">Press Kit</li>
</ol>

h1.page-header.header-light Press Kit

.row
  .col-sm-7
    .about-text
      p The following press kit contains:
      ul
        li 
          p High-quality logo
        li 
          p High-quality photographs of founders
        li 
          p High-quality photos of team
        li 
          p High-quality photographs of SV Kochi location
        li 
          p High-quality photographs of the SV Vizag location
        li 
          p Product screenshots
      p
        a class="btn btn-primary" href="#{@press_kit_url}" target="_blank"
         span class="glyphicon glyphicon-download-alt" 
           '  Download

  .col-sm-3
    = render partial: 'about_links'

app/views/home/slack.html.slim
- content_for :head
  = stylesheet_link_tag 'about'
  
<ol class="breadcrumb">
  <li><a href="#{root_path}">Home</a></li>
  <li><a href="#{about_path}">About</a></li>
  <li class="active">Public Slack</li>
</ol>

h1.page-header.header-light Public Slack Forum

.row
  .col-sm-7
    #transparency-intiative.about-text
      p SV.CO has a public slack forum for discussion by the community. Members from the SV.CO team are often online and you'll get quick answers to your queries. Almost all our communication with registered members of SV.CO is also through this channel, so you'll get a feel for how our community works.

      p To sign up, join below. By joining, you read and agree to the <a href="http://playbook.sv.co/8-code-of-conduct.html">Community Code of Conduct</a>.
      
      iframe class="slack" src="https://svlabs-public.herokuapp.com" scrolling="no" seamless="seamless"
  
  .col-sm-3
    = render partial: 'about_links'

app/views/home/test_background.html.slim
h1 Test Background

.full-screen-background class="background-image-#{background_image_number}"
  .hero-text class="hero-text-#{hero_text_alignment}"
    | This is the hero text.