config/routes.rb
Svapp::Application.routes.draw do
  get 'user/identify'

  devise_for(
    :founders,
    controllers: {
      invitations: 'founders/invitations',
      sessions: 'founders/sessions'
    }
  )

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]

  resource :founder, only: [:edit, :update] do
    member do
      get 'phone'
      patch 'set_unconfirmed_phone'
      get 'phone_verification'
      post 'code'
      patch 'resend'
      post 'verify'
    end

    collection do
      patch 'update_password'
    end

    resource :startup, only: [:new, :create, :edit, :update, :destroy] do
      post :add_founder
      patch :remove_founder
      patch :change_admin

      resources :timeline_events, only: [:create, :destroy, :update]
      resources :team_members, except: [:index]
    end
  end

  resources :startups, only: [:index, :show] do
    collection do
      post 'team_leader_consent'
    end

    resources :timeline_events, only: [] do
      resources :timeline_event_files, only: [] do
        member do
          get 'download'
        end
      end
    end
  end

  scope 'about', as: 'about', controller: 'about' do
    get '/', action: 'index'
    get 'slack'
    get 'media-kit'
    get 'leaderboard'
    get 'contact'
    post 'contact', action: 'send_contact_email'
  end

  resources :faculty, only: %w(index show) do
    post 'connect', on: :member
    collection do
      get 'filter/:active_tab', to: 'faculty#index'
      get 'weekly_slots/:token', to: 'faculty#weekly_slots', as: 'weekly_slots'
      post 'save_weekly_slots/:token', to: 'faculty#save_weekly_slots', as: 'save_weekly_slots'
      get 'mark_unavailable/:token', to: 'faculty#mark_unavailable', as: 'mark_unavailable'
      get 'slots_saved/:token', to: 'faculty#slots_saved', as: 'slots_saved'
    end
  end

  scope 'library', controller: 'resources' do
    get '/', action: 'index', as: 'resources'
    get '/:id', action: 'show', as: 'resource'
    get '/:id/download', action: 'download', as: 'download_resource'
  end

  get 'resources/:id', to: redirect('/library/%{id}')

  scope 'connect_request', controller: 'connect_request', as: 'connect_request' do
    get ':id/feedback/from_team/:token', action: 'feedback_from_team', as: 'feedback_from_team'
    get ':id/feedback/from_faculty/:token', action: 'feedback_from_faculty', as: 'feedback_from_faculty'
    get ':id/join_session(/:token)', action: 'join_session', as: 'join_session'
  end

  scope 'talent', as: 'talent', controller: 'talent' do
    get '/', action: 'index'
    post 'contact'
  end

  scope 'apply', as: 'apply', controller: 'batch_application' do
    get '', action: 'index'
    post 'register'
    get 'identify'
    post 'send_sign_in_email'
    get 'sign_in_email_sent'
    get 'continue'
    post 'restart'

    scope 'stage/:stage_number', as: 'stage' do
      get '', action: 'ongoing'
      post 'submit'
      get 'complete'
      get 'expired'
      get 'rejected'
    end
  end

  resource :platform_feedback, only: [:create]

  # Redirect + webhook from Instamojo
  scope 'instamojo', as: 'instamojo', controller: 'instamojo' do
    get 'redirect'
    post 'webhook'
  end

  # Custom founder profile page.
  get 'founders/:slug', to: 'founders#founder_profile', as: 'founder_profile'

  # Story of startup village, accessed via about pages.
  get 'story', as: 'story', to: 'home#story'

  # Previous transparency page re-directed to story
  get 'transparency', to: redirect('/story')

  # Activity from startups.
  get 'activity', as: 'activity', to: 'timeline_events#activity'

  # Public Changelog.
  get 'changelog', to: 'home#changelog'

  # Application process tour of SV.CO
  get 'tour', to: 'home#tour'

  root 'home#index'

  # custom defined 404 route to use with shortener gem's config
  get '/404', to: 'home#not_found'

  # to test rotating background images.
  get '/test_background', to: 'home#test_background'

  # Previous sixways page re-directed to startincollege
  # get 'sixways', to: redirect('/startincollege')

  # Also have /StartInCollege
  get 'StartInCollege', to: redirect('/startincollege')

  scope 'policies', as: 'policies', controller: 'home' do
    get 'privacy'
    get 'terms'
  end

  scope 'startincollege', as: 'start_in_college', controller: 'start_in_college' do
    get '/', action: 'index'
    get 'start'
    get 'student_details'
    post 'create_student'
    # TODO: why is a patch request send after a few rounds of errors ?
    post 'save_student_details'
    patch 'save_student_details'
    get 'chapter/:id/:section_id', action: 'chapter', as: 'chapter'
    get 'quiz/:id', action: 'quiz', as: 'quiz'
    post 'quiz_submission'
    get 'course_end'
  end

  # used for shortened urls from the shortener gem
  get '/:id', to: 'shortener/shortened_urls#show'

  scope 'user_sessions', as: 'user_sessions', controller: 'user_sessions' do
    get 'new'
    post 'send_email'
    patch 'send_email'
  end
end

app/views/resources/_resource.html.slim
.col-md-3.col-sm-4
  .resource
    - if resource.thumbnail.present?
      = image_tag resource.thumbnail.url
    - else
      = image_tag 'resources/thumbnail_default.png', class: 'img-responsive'
    - if resource.for_approved?
      .batch-exclusive
        .badge Batch Exclusive

    .resource-content
      .title
        = link_to resource.title, resource
      .description
        = simple_format resource.description

    .links
      - if resource.stream?
        = link_to resource_url(resource, watch: true), class: 'btn stream-resource material-btn green', title: "Play" do
          i.fa.fa-play

      a.btn.material-btn.blue href=download_resource_url(resource) target='_blank' title="Download"
        i.fa.fa-download

app/views/resources/_tags.html.slim
.resources-show-tags
  - resource.tags.each do |tag|
    = link_to resources_path('tags[]' => tag.name) do
      span.label.label-info = tag.name

app/views/resources/index.html.slim
- content_for :head
  title SV.CO Library for First-time Founders
  meta name="description" content="Get access to content produced by Startup Village faculty, including presentations, video and audio clips."

.resources-banner-bg
  .container
    .resources-banner
      .banner-text.text-center
        h1.page-header.header-light Library
        p.startups-introduction
          ' This is just a small sample of resources available in the SV.CO Library. Approved Startups
          | get access to exclusive content produced by Faculty, including presentations, video and audio clips.

.resources-bg
  .container
    - if current_founder.present? && (@resources.count > Resource.public_resources.count)
      .alert.alert-warning
        ' You currently have access to exclusive resources that are marked clearly by a <strong>Batch Exclusive</strong>
        | badge. Please do not share these resources outside your founding team. Thank you!

    .resources
      .tag-filter
        = form_tag nil, method: "get" do
          = select_tag "tags", options_for_select(@resource_tags, params[:tags]), multiple: true, include_blank: true, id: "resources-index-tags", class: "tag-select"
          = text_field_tag "search", params[:search], placeholder: 'Title contains', class: 'search-field'
          = button_tag name: "Filter", type: "submit", class: 'btn btn-primary tag-filter-btn text-uppercase' do
            i.fa.fa-filter
            | Filter
          - if params[:tags].present? || params[:search].present?
            = link_to resources_path, class: 'btn btn-primary tag-filter-clear text-uppercase' do
              i.fa.fa-refresh
              | Clear Filter

      .row
        - if @resources.blank?
          .col-md-12
            .alert.alert-warning
              = zero_results_text.html_safe
        - else
          - if params[:tags].present? || params[:search].present?
            p.grey-text.show-result-text
              = results_caption
          - @resources.each do |resource|
            = render 'resource', resource: resource
    .text-center
      = will_paginate @resources, renderer: BootstrapPagination::Rails

app/views/resources/show.html.slim
- content_for :head
  title SV.CO #{@resource.title}

ol.breadcrumb.margin-top-20
  li = link_to 'Home', root_path
  li = link_to 'Library', resources_path
  li.active = @resource.title

h1.page-header.header-light #{@resource.title}

- if @stream_video
  .resource-play.margin-bottom-20
  = videojs_rails sources: { mp4: @stream_video}, class: 'img-responsive resource-show-video'
  .resource-show-description = simple_format @resource.description

  == render 'tags', resource: @resource

  a.btn.btn-primary.btn-download href=download_resource_url(@resource) target='_blank'
    i.fa.fa-download
    | &nbsp; Download
- else
  .resource-show.clearfix.margin-bottom-20
    - if @resource.thumbnail.present?
      = image_tag @resource.thumbnail.url
    - else
      = image_tag 'resources/thumbnail_default.png'
    - if @resource.for_approved?
      .batch-exclusive
        .badge Batch Exclusive

    .content class="#{@stream_video ? 'stream' : nil}"
      .content-inner
        .resource-show-description = simple_format @resource.description

        == render 'tags', resource: @resource

        - if @resource.stream?
          = link_to resource_url(@resource, watch: true), class: 'btn btn-success btn-play stream-resource' do
            i.fa.fa-play
            | &nbsp; Play

        a.btn.btn-primary.btn-download href=download_resource_url(@resource) target='_blank'
          i.fa.fa-download
          | &nbsp; Download

hr.margin-top-20

= link_to resources_path, class: 'btn btn-default margin-bottom-40' do
  i.fa.fa-chevron-left
  | &nbsp; See all available resources