config/routes.rb
Svapp::Application.routes.draw do
  get 'user/identify'

  devise_for(
    :founders,
    controllers: {
      invitations: 'founders/invitations',
      sessions: 'founders/sessions'
    }
  )

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  match '/delayed_job' => DelayedJobWeb, anchor: false, via: [:get, :post]

  resource :founder, only: [:edit, :update] do
    member do
      get 'phone'
      patch 'set_unconfirmed_phone'
      get 'phone_verification'
      post 'code'
      patch 'resend'
      post 'verify'
    end

    collection do
      patch 'update_password'
    end

    resource :startup, only: [:new, :create, :edit, :update, :destroy] do
      post :add_founder
      patch :remove_founder
      patch :change_admin

      resources :timeline_events, only: [:create, :destroy, :update]
      resources :team_members, except: [:index]
    end
  end

  resources :startups, only: [:index, :show] do
    collection do
      post 'team_leader_consent'
    end

    resources :timeline_events, only: [] do
      resources :timeline_event_files, only: [] do
        member do
          get 'download'
        end
      end
    end
  end

  scope 'about', as: 'about', controller: 'about' do
    get '/', action: 'index'
    get 'slack'
    get 'media-kit'
    get 'leaderboard'
    get 'contact'
    post 'contact', action: 'send_contact_email'
  end

  resources :faculty, only: %w(index show) do
    post 'connect', on: :member
    collection do
      get 'filter/:active_tab', to: 'faculty#index'
      get 'weekly_slots/:token', to: 'faculty#weekly_slots', as: 'weekly_slots'
      post 'save_weekly_slots/:token', to: 'faculty#save_weekly_slots', as: 'save_weekly_slots'
      get 'mark_unavailable/:token', to: 'faculty#mark_unavailable', as: 'mark_unavailable'
      get 'slots_saved/:token', to: 'faculty#slots_saved', as: 'slots_saved'
    end
  end

  scope 'library', controller: 'resources' do
    get '/', action: 'index', as: 'resources'
    get '/:id', action: 'show', as: 'resource'
    get '/:id/download', action: 'download', as: 'download_resource'
  end

  get 'resources/:id', to: redirect('/library/%{id}')

  scope 'connect_request', controller: 'connect_request', as: 'connect_request' do
    get ':id/feedback/from_team/:token', action: 'feedback_from_team', as: 'feedback_from_team'
    get ':id/feedback/from_faculty/:token', action: 'feedback_from_faculty', as: 'feedback_from_faculty'
    get ':id/join_session(/:token)', action: 'join_session', as: 'join_session'
  end

  scope 'talent', as: 'talent', controller: 'talent' do
    get '/', action: 'index'
    post 'contact'
  end

  scope 'apply', as: 'apply', controller: 'batch_application' do
    get '', action: 'index'
    post 'register'
    get 'identify'
    post 'send_sign_in_email'
    get 'sign_in_email_sent'
    get 'continue'
    post 'restart'

    scope 'stage/:stage_number', as: 'stage' do
      get '', action: 'ongoing'
      post 'submit'
      get 'complete'
      get 'expired'
      get 'rejected'
    end
  end

  resource :platform_feedback, only: [:create]

  # Redirect + webhook from Instamojo
  scope 'instamojo', as: 'instamojo', controller: 'instamojo' do
    get 'redirect'
    post 'webhook'
  end

  # Custom founder profile page.
  get 'founders/:slug', to: 'founders#founder_profile', as: 'founder_profile'

  # Story of startup village, accessed via about pages.
  get 'story', as: 'story', to: 'home#story'

  # Previous transparency page re-directed to story
  get 'transparency', to: redirect('/story')

  # Activity from startups.
  get 'activity', as: 'activity', to: 'timeline_events#activity'

  # Public Changelog.
  get 'changelog', to: 'home#changelog'

  # Application process tour of SV.CO
  get 'tour', to: 'home#tour'

  root 'home#index'

  # custom defined 404 route to use with shortener gem's config
  get '/404', to: 'home#not_found'

  # to test rotating background images.
  get '/test_background', to: 'home#test_background'

  # Previous sixways page re-directed to startincollege
  # get 'sixways', to: redirect('/startincollege')

  # Also have /StartInCollege
  get 'StartInCollege', to: redirect('/startincollege')

  scope 'policies', as: 'policies', controller: 'home' do
    get 'privacy'
    get 'terms'
  end

  scope 'startincollege', as: 'start_in_college', controller: 'start_in_college' do
    get '/', action: 'index'
    get 'start'
    get 'student_details'
    post 'create_student'
    # TODO: why is a patch request send after a few rounds of errors ?
    post 'save_student_details'
    patch 'save_student_details'
    get 'chapter/:id/:section_id', action: 'chapter', as: 'chapter'
    get 'quiz/:id', action: 'quiz', as: 'quiz'
    post 'quiz_submission'
    get 'course_end'
  end

  # used for shortened urls from the shortener gem
  get '/:id', to: 'shortener/shortened_urls#show'

  scope 'user_sessions', as: 'user_sessions', controller: 'user_sessions' do
    get 'new'
    post 'send_email'
    patch 'send_email'
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  rescue_from ActionView::MissingTemplate, with: -> { raise_not_found }

  # GET /about
  def index
    @sitewide_notice = params[:redirect_from] == 'startupvillage.in'
  end

  # GET /about/slack
  def slack
  end

  # GET /about/leaderboard
  def leaderboard
  end

  # GET /about/press-kit
  def media_kit
    @media_kit_url = 'https://drive.google.com/folderview?id=0B9--SdQuJvHpfjJiam1nTnJCNnVIYkY2NVFXWTQwbXNpWUFoQU1oc1RZSHJraG4yb2Y1cDA&usp=sharing'
  end

  # GET /about/contact
  def contact
    @contact_form = ContactForm.new(founder: current_founder)
    @sitewide_notice = params[:redirect_from] == 'startupvillage.in'
  end

  # POST /about/contact
  def send_contact_email
    @contact_form = ContactForm.new contact_form_params

    # Check recaptcha first.
    unless verify_recaptcha(model: @contact_form)
      render 'contact'
      return
    end

    if @contact_form.save
      flash[:success] = "An email with your query has been sent to help@sv.co. We'll get back to you as soon as we can."
      redirect_to about_contact_path
    else
      flash.now[:error] = 'Please make sure that you filled out all required fields in the contact form.'
      render 'contact'
    end
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :email, :mobile, :company, :query_type, :query)
  end
end

app/views/about/_about_links.html.slim
#about-links
  .list-group
    a.list-group-item href="#{about_contact_path}" Contact
  h4.header-light Press & Media
  .list-group
    a.list-group-item href="#{about_media_kit_path}" Media Kit
    a.list-group-item href="#{about_slack_path}" Slack
    a.list-group-item href="mailto:help@sv.co" Email help@sv.co
  h4.header-light Startups
  .list-group
    a.list-group-item href="#{about_leaderboard_path}" Leaderboard

  h4.header-light Social Media
  .list-group
    a.list-group-item href="https://www.youtube.com/c/svdotco"
      | Youtube Channel
      i.fa.fa-youtube.pull-right
    a.list-group-item href="https://twitter.com/svdotco"
      | Twitter Account
      i.fa.fa-twitter.pull-right
    a.list-group-item href="https://www.facebook.com/svdotco"
      | Facebook Page
      i.fa.fa-facebook.pull-right

app/views/about/contact.html.slim
- if @sitewide_notice
  - content_for :sitewide_notice
    ' <strong>SV.CO</strong> is the next phase of the Startup Village story.
    ' #{link_to 'Read more here', 'https://sv.co/cwlg8', class: 'btn btn-sm', target: '_blank'}

- content_for :head
  title SV.CO Contact Details
  meta name="description" content="Contact the Startup Village team at help@sv.co. Mingle with the community on our Public Slack Forum. Or drop by at our campuses at Kochi and Visakhapatnam."

ol.breadcrumb class="#{@sitewide_notice.present? ? 'margin-top-60' : 'margin-top-20'}"
  li = link_to 'Home', root_path
  li = link_to 'About', about_path
  li.active Contact

h1.page-header.header-light Contact

.row
  .col-sm-8
    .contact-container
      p
        ' Send us an e-mail at #{mail_to 'help@sv.co'}, and we'll get back to you as soon as we can. The
        a href="#new_contact_form" <em>form</em> at the bottom of this page
        | &nbsp;can help with that!

      p.margin-bottom-20
        ' Alternatively, join our #{link_to 'Public Slack Forum', about_slack_path}, to get in contact with both the
        | SV.CO team, and the community.

      .row.margin-bottom-10
        .col-md-6
          .contact-location
            .google-maps-iframe-container
              iframe.contact-google-map frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/view?zoom=16&center=12.93116%2C77.63232&key=#{ENV['GOOGLE_BROWSER_KEY']}" allowfullscreen=true sandbox="allow-same-origin allow-scripts"
            address
              strong SV.CO
              br
              p
                | 1st floor, atop Cafe Coffee Day,
                br
                | Opp. The Beer Cafe,
                br
                | 4th Block Main Road,
                br
                | 80 Feet Main Rd,
                br
                | Koramangala 4th Block,
                br
                | Bengaluru &mdash; 560095

      = simple_form_for @contact_form,
        url: about_contact_url,
        method: :post,
        html: { class: 'form-horizontal' },
        wrapper: :horizontal_form,
        wrapper_mappings: { check_boxes: :horizontal_radio_and_checkboxes, radio_buttons: :horizontal_radio_and_checkboxes, file: :horizontal_file_input, boolean: :horizontal_boolean } do |f|

        legend Contact Form

        = f.input :name, label: 'Your name', input_html: { maxlength: 50 }
        = f.input :email, type: 'email', label: 'Email address', input_html: { maxlength: 50 }
        = f.input :mobile, label: 'Mobile phone number', input_html: { maxlength: 20 }
        = f.input :company, label: 'Company you represent', input_html: { maxlength: 50 }
        = f.input :query_type, label: 'Type of query', as: :select, include_blank: false, collection: ContactForm.valid_query_types
        #contact-alerts.col-sm-9.col-sm-offset-3.alert.alert-warning
        = f.input :query, as: :text, input_html: { rows: 5, maxlength: 600 }

        .form-group
          .col-sm-9.col-sm-offset-3
            = recaptcha_tags
            = button_tag type: :submit, class: 'btn btn-primary contact-submit-button' do
              i.fa.fa-send
              | &nbsp;Submit
  .col-md-3.col-md-offset-1.col-sm-4
    = render 'about_links'

app/views/about/index.html.slim
- if @sitewide_notice
  - content_for :sitewide_notice
    ' <strong>SV.CO</strong> is the next phase of the Startup Village story.
    ' #{link_to 'Read more here', 'https://sv.co/cwlg8', class: 'btn btn-sm', target: '_blank'}

- content_for :head
  title About SV.CO: A learning platform for first-time founders
  meta name="description" content="Startup Village is launching an online-first learning platform for first-time founders, supplying tools and resources needed to create a successful startup."

ol.breadcrumb class="#{@sitewide_notice.present? ? 'margin-top-60' : 'margin-top-20'}"
  li = link_to 'Home', root_path
  li.active About

h1.page-header.header-light About Startup Village

.row
  .col-sm-8
    #about-main.about-text
      p At SV.CO we are building an online University for student founders.

      p We believe young founders today are special. Never before in history has it been possible for so few to build products for so many. We have a unique opportunity to teach <i>everyone</i> how to build great startups, right in school and college.

      p Many who learn will go on to build long-lived, thriving companies that'll shape our future. Many more will pick up great skills, knowledge and enriching experiences that can help them become interesting and amazing people: the kind of people who will make a difference in our world.

      hr

      p We're best known for our inclusive public-private partnership incubator based in Kochi that has <a href="http://yourstory.com/2015/05/startup-village-national-award/">won numerous awards</a> and created stellar startups. The incubator was started in April 2012 as a joint partnership with the Government of India through the <a href="http://www.dst.gov.in">Department of Science and Technology</a>, <a href="http://www.technoparktbi.org">Technopark TBI</a> and our host-institute, <a href="http://mobme.in">MobME Wireless</a>.

      p Building on our knowledge acquired from mentoring startups, ​we're now ​an online-first learning platform for first-time founders. SV.CO is the first learning platform for entrepreneurship that verifies results & rewards founders with a real degree by partnering with ​​recognised Universities.

  .col-md-3.col-md-offset-1.col-sm-4
    = render partial: 'about_links'

app/views/about/leaderboard.html.slim
- content_for :head
  title SV.CO Leaderboard
  meta name="description" content="SV.CO tracks startups' progress using the Startup Village leaderboard, showing startups that have improved the most compared to the previous leaderboard."

ol.breadcrumb.margin-top-20
  li = link_to 'Home', root_path
  li = link_to 'About', about_path
  li.active Leaderboards

h1.page-header.header-light
  | Leaderboard
  - if Startup.available_batches.live.present?
    small &nbsp;#{Startup.leaderboard_start_date.strftime('%B %-d')} to #{Startup.leaderboard_end_date.strftime('%B %-d')}

.row
  .col-sm-8
    .about-text
      p
        ' Leaderboards are how we track progress for our startups. They <strong>don't show</strong> the best startups at
        ' SV.CO. Rather, they show <strong>startups that have improved the most</strong> compared to the previous
        | leaderboard.

      p Please read the <a href="http://playbook.sv.co/3.1-leaderboards.html">Leaderboards</a> page on the Playbook.

      div
        - if Startup.available_batches.live.present?
          ul.nav.nav-tabs role="tablist"
            - Startup.available_batches.live.each_with_index do |batch, index|
              li class="#{index==0 ? "active" : ""}" role="presentation"
                a href="##{batch.name}" aria-controls="#{batch.name}" role="tab" data-toggle="tab" #{batch.name} Batch

          .tab-content
            - Startup.available_batches.live.each_with_index do |batch, index|
              .tab-pane.fade class="#{index==0 ? "in active" : ""}" id="#{batch.name}" role="tabpanel"
                table.table.table-striped
                  thead
                    tr
                      th Rank
                      th Product
                      th Team Lead
                  tbody
                    - Startup.leaderboard_of_batch(batch).each_with_index do |rank_array, index|
                      - startup_id, rank = rank_array
                      - startup = Startup.find(startup_id)
                      tr
                        td = rank
                        td = link_to "#{startup.product_name} #{startup.name.present? ? "(#{startup.name})" : ''}", startup_path(startup)
                        td = startup.admin.try(:fullname)

                    - startups_without_karma, rank = Startup.without_karma_and_rank_for_batch(batch)
                    - startups_without_karma.each do |startup|
                      tr
                        td = rank
                        td = link_to "#{startup.product_name} #{startup.name.present? ? "(#{startup.name})" : ''}", startup_path(startup)
                        td = startup.admin.try(:fullname)
        - else
         p.alert.alert-warning It appears there are no live batches in SV.CO now! Please check back later for leaderboard of our new batches.

  .col-md-3.col-md-offset-1.col-sm-4
    = render partial: 'about_links'

app/views/about/media_kit.html.slim
- content_for :head
  title SV.CO Media/Press Kit
  meta name="description" content="Download a write-up of SV.CO, high quality logos, photographs of founders and team members, and pictures of our campuses at Kochi and Visakhapatnam."

ol.breadcrumb.margin-top-20
  li = link_to 'Home', root_path
  li = link_to 'About', about_path
  li.active Media Kit

h1.page-header.header-light Media Kit

.row
  .col-sm-8
    .about-text
      p The following media kit contains:
      ul
        li
          p A write-up of SV.CO
        li
          p High-quality logos
        li
          p High-quality photographs of founders
        li
          p High-quality photos of team
        li
          p High-quality photographs of SV Kochi location
        li
          p High-quality photographs of the SV Vizag location
        li
          p Product screenshots
      p
        a class="btn btn-primary" href="#{@media_kit_url}" target="_blank"
          span class="glyphicon glyphicon-download-alt"
            '  Download

  .col-md-3.col-md-offset-1.col-sm-4
    = render partial: 'about_links'

app/views/about/officehours.html.slim
- content_for :head
  = stylesheet_link_tag 'about'

ol.breadcrumb.margin-top-20
  li = link_to 'Home', root_path
  li = link_to 'About', about_path
  li.active Office-hours

h1.page-header.header-light Faculty Office Hours

.row
  .col-sm-8
    iframe.office-hours-calendar src="https://www.google.com/calendar/embed?showTitle=0&showPrint=0&showCalendars=0&src=help%40sv.co&ctz=Asia/Calcutta"
  .col-md-3.col-md-offset-1.col-sm-4
    = render partial: 'about_links'

app/views/about/press_kit.html.slim
- content_for :head
  = stylesheet_link_tag 'about'

ol.breadcrumb.margin-top-20
  li = link_to 'Home', root_path
  li = link_to 'About', about_path
  li.active Press Kit

h1.page-header.header-light Press Kit

.row
  .col-sm-8
    .about-text
      p The following press kit contains:
      ul
        li
          p High-quality logo
        li
          p High-quality photographs of founders
        li
          p High-quality photos of team
        li
          p High-quality photographs of SV Kochi location
        li
          p High-quality photographs of the SV Vizag location
        li
          p Product screenshots
      p
        a class="btn btn-primary" href="#{@press_kit_url}" target="_blank"
          span class="glyphicon glyphicon-download-alt"
            '  Download

  .col-md-3.col-md-offset-1.col-sm-4
    = render partial: 'about_links'

app/views/about/slack.html.slim
- content_for :head
  title SV.CO Public Slack for Discussion
  meta name="description" content="Get your queries answered directly by SV.CO team members, and mingle with the Startup Village community on our Public Slack Forum."

ol.breadcrumb.margin-top-20
  li = link_to 'Home', root_path
  li = link_to 'About', about_path
  li.active Public Slack

h1.page-header.header-light Public Slack Forum

.row
  .col-sm-8
    #transparency-intiative.about-text
      p SV.CO has a public slack forum for discussion by the community. Members from the SV.CO team are often online and you'll get quick answers to your queries. Almost all our communication with registered members of SV.CO is also through this channel, so you'll get a feel for how our community works.

      p To sign up, join below. By joining, you read and agree to the <a href="http://playbook.sv.co/8-code-of-conduct.html">Community Code of Conduct</a>.

      iframe class="slack" src="https://svlabs-public.herokuapp.com" scrolling="no" seamless="seamless" sandbox="allow-same-origin allow-scripts"

  .col-md-3.col-md-offset-1.col-sm-4
    = render partial: 'about_links'